<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML><HEAD>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta http-equiv="Content-Language" content="en-us">
<meta name="GENERATOR" content="Microsoft FrontPage 4.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<meta name="description" content="Explication de la matière et de tous les phénomènes physiques par des ondes stationnaires.">
<meta name="keywords" content="matière, ondes stationnaires, Michelson, Lorentz, Relativité, gravité, électron, quark, gluon, atome, lumière, champ magnétique">
<TITLE>Error</TITLE>

</HEAD>
<BODY bgColor=#E1E1E1>
  <p align="center"><font face="Times New Roman" size="4">&nbsp;&nbsp;&nbsp;</font></p>
  <p align="center"><font face="Times New Roman" size="4">&nbsp;&nbsp;&nbsp;</font></p>
  <p align="center"><font face="Times New Roman" size="4">&nbsp;&nbsp;&nbsp;</font></p>
  <div align="center">
    <center>
    <table border="6" cellpadding="16" cellspacing="6">
      <tr>
        <td>
          <p align="center"><font size="4" face="Times New Roman">&nbsp;&nbsp;&nbsp;&nbsp;</font></p>
  <P align=center><font face="Times New Roman" size="5"><b>404&nbsp;Error - File not
  found.</b></font> 
        
  </P>
          <p align="center"><font face="Times New Roman" size="5"><b><a href="matter.htm">Home
          Page</a></b></font>
          <p align="center"><font size="4" face="Times New Roman">&nbsp;&nbsp;&nbsp;&nbsp;</font></p>
        </td>
        <td>
          <p align="center"><font size="4" face="Times New Roman">&nbsp;&nbsp;&nbsp;&nbsp;</font></p>
  <P align=center><font face="Times New Roman" size="5"><b>Erreur 404</b></font><font face="Times New Roman" size="5"><b> -
  </b></font> 
        
  <font face="Times New Roman" size="5"><b>Fichier absent.</b></font> 
        
  </P>
          <p align="center"><font face="Times New Roman" size="5"><b><a href="matiere.htm">Page
          d'accueuil.</a></b></font>
          <p align="center"><font size="4" face="Times New Roman">&nbsp;&nbsp;&nbsp;&nbsp;</font></p>
        </td>
      </tr>
    </table>
    </center>
  </div>
  <p align="center"><font face="Times New Roman" size="4">&nbsp;&nbsp;</font></p>
</BODY></HTML>
<!-- text below generated by server. PLEASE REMOVE -->