<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML><HEAD>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta http-equiv="Content-Language" content="en-us">
<meta name="GENERATOR" content="Microsoft FrontPage 4.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<meta name="description" content="Explication de la matière et de tous les phénomènes physiques par des ondes stationnaires.">
<meta name="keywords" content="matière, ondes stationnaires, Michelson, Lorentz, Relativité, gravité, électron, quark, gluon, atome, lumière, champ magnétique">
<TITLE>Error</TITLE>

</HEAD>
<BODY bgColor=#E1E1E1>
  <P align=center><font face="Times New Roman" size="5"><b>404&nbsp;Error - File not
  found.</b></font> 
        
  </P>
  <p align="center"><font face="Times New Roman" size="4">Click here: <a href="matter.htm"> home
  page</a>
  or&nbsp;select a page in the list below.</font></p>

  <font face="Times New Roman" size="4">
  <p align="center"><span class="white">| <a href="matter.htm">01</a> | <a href="sa_electron.htm">02</a>
  | <a href="sa_plane.htm">03</a> | <a href="sa_spherical.htm">04</a> | <a href="sa_Doppler.htm">05</a>
  | <a href="sa_aether.htm">06</a> | <a href="sa_Michelson.htm">07</a> | <a href="sa_Lorentz.htm">08</a>
  | <a href="sa_scanner.htm">09</a> | <a href="sa_relativity.htm">10</a> | <a href="sa_relativity2.htm">11</a>
  | </span><a href="sa_phaseshift.htm">12</a><span class="white"> | </span><a href="sa_mechanics.htm">13</a><span class="white">
  | </span><a href="sa_electrostatic.htm">14</a><span class="white"> | </span><a href="sa_nuclear.htm">15</a><span class="white">
  | </span><a href="sa_active.htm">16</a><span class="white"> |</span></p>
  <p align="center"><span class="white">| </span><a href="sa_kinetic.htm">17</a><span class="white">
  | </span><a href="sa_fields.htm">18</a><span class="white"> | </span><a href="sa_dynamics.htm">19</a><span class="white">
  | </span><a href="sa_magnetic.htm">20</a><span class="white"> | </span><a href="sa_gravity.htm">21</a><span class="white">
  | </span><a href="sa_light.htm">22</a><span class="white"> | <a href="sa_quarks.htm">23</a>
  | </span><a href="sa_protons.htm">24</a><span class="white"> | </span><a href="sa_atoms.htm">25</a><span class="white">
  | </span><a href="sa_chemistry.htm">26</a><span class="white"> | </span><a href="sa_wavetheory.htm">27</a><span class="white">
  | </span><a href="sa_postulates.htm">28</a><span class="white"> | </span><a href="sa_evolution.htm">29</a><span class="white">
  | <a href="sa_errors.htm">30</a> | <a href="sa_experiences.htm">31</a> | </span><a href="sa_Huygens.htm">32</a><span class="white">
  | </span><a href="sa_conclusion.htm">33</a><span class="white"> |</span></p>
  </font>
  <p align="center"><font face="Times New Roman" size="4">Gabriel LaFreniere&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <a href="the_blog.htm">The Blog</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Email: <a href="notice.htm">Please
  read this notice.</a></font></p>

  <p align="center"><font face="Times New Roman" size="4">&nbsp;&nbsp; </font></p>
  <P align=center><font face="Times New Roman" size="4">La <a href="matiere.htm">version
  française</a>&nbsp;n'est plus à jour et sera retirée éventuellement.</font> 
        
  </P>
  <P align=center><font face="Times New Roman" size="4">(The <a href="matiere.htm"> French
  Version</a> is
  obsolete and may be removed.)</font> 
        
  </P>
</BODY></HTML>
<!-- text below generated by server. PLEASE REMOVE -->